### ISSUE TITLE
Design Cart Page UI

### ISSUE THREAD

**Issue by Abrar-Abdulwahed** [202212-GIZ-YE-FEW/react-ecommerce-fiftystore#6]
- [x] Design List of selected items.
- [ ] for each item row, should have this features:
> - [ ] remove item
> - [ ] increase/decrease quantity
> - [ ] field for quantity.
> - [ ] cost.
- [ ] Total cost.
- [ ] Design (Proceed to Checkout) button.

**Comment by Jehadalmaliki** [comment]
Cart-UI
